//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaPeliculas.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CursoMVCEntities : DbContext
    {
        public CursoMVCEntities()
            : base("name=CursoMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Peliculas> Peliculas { get; set; }
    
        public virtual int CrudClientes(Nullable<System.Guid> idCliente, string nombre, string apellido, string correo, string telefono, Nullable<short> accion)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrudClientes", idClienteParameter, nombreParameter, apellidoParameter, correoParameter, telefonoParameter, accionParameter);
        }
    
        public virtual ObjectResult<GetClientes_Result> GetClientes(Nullable<System.Guid> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClientes_Result>("GetClientes", idClienteParameter);
        }
    
        public virtual int CrudRentas(Nullable<System.Guid> idRentas, Nullable<System.Guid> idPelicula, Nullable<System.Guid> idCliente, Nullable<System.DateTime> fecha, Nullable<short> accion)
        {
            var idRentasParameter = idRentas.HasValue ?
                new ObjectParameter("IdRentas", idRentas) :
                new ObjectParameter("IdRentas", typeof(System.Guid));
    
            var idPeliculaParameter = idPelicula.HasValue ?
                new ObjectParameter("IdPelicula", idPelicula) :
                new ObjectParameter("IdPelicula", typeof(System.Guid));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrudRentas", idRentasParameter, idPeliculaParameter, idClienteParameter, fechaParameter, accionParameter);
        }
    
        public virtual ObjectResult<GetRentas_Result> GetRentas(Nullable<System.Guid> idRentas, Nullable<System.Guid> idPelicula, Nullable<System.Guid> idCliente)
        {
            var idRentasParameter = idRentas.HasValue ?
                new ObjectParameter("IdRentas", idRentas) :
                new ObjectParameter("IdRentas", typeof(System.Guid));
    
            var idPeliculaParameter = idPelicula.HasValue ?
                new ObjectParameter("IdPelicula", idPelicula) :
                new ObjectParameter("IdPelicula", typeof(System.Guid));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRentas_Result>("GetRentas", idRentasParameter, idPeliculaParameter, idClienteParameter);
        }
    }
}
